accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from .views import *

urlpatterns = [
    # Accounts
    path('', accounts, name='accounts'),
    path('search_accounts', search_accounts, name='search_accounts'),
    path('create_account/', create_account, name='create_account'),
    path('update_account/<int:pk>/', update_account, name='update_account'),
    path('delete_account/<int:pk>/', delete_account, name='delete_account'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('deactivate_account/<int:pk>/', deactivate_account, name='deactivate_account'),
    # Password
    path('password_reset/',
        auth_views.PasswordResetView.as_view(
            template_name            = 'password/password_reset.html',
            html_email_template_name = 'email/password_reset_email.html',
            subject_template_name    = 'email/password_reset_subject.txt',
            ),
            name                     = 'password_reset'
        ),
    path('password_reset_done/', password_reset_done, name = 'password_reset_done'),
    path('reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            # success_url   = 'sign_in',
            template_name = 'password/password_reset_confirm.html',
            ),
            name          = 'password_reset_confirm'
        ),
    path('reset/done/', password_reset_complete, name = 'password_reset_complete'),
    path('password_change/',
        auth_views.PasswordChangeView.as_view(
            template_name = 'password/password_change.html',
            ),
            name          = 'password_change'
        ),
    path('password_change_done/', password_change_done, name = 'password_change_done'),
]

dockingRecords/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    # Records
    path('flight_schedule', flight_schedule, name='flight_schedule'),
    path('dockings', dockings, name='dockings'),
    path('arrival_schedule', arrival_schedule, name='arrival_schedule'),
    path('departure_schedule', departure_schedule, name='departure_schedule'),
    path('search_records', search_records, name='search_records'),
    path('create_docking', create_docking, name='create_docking'),
    path('create_docking_fids/<str:iata>', create_docking_fids, name='create_docking_fids'),
    path('create_undocking/<int:pk>', create_undocking, name='create_undocking'),
    path('create_nodocking', create_nodocking, name='create_nodocking'),
    path('update_record/<int:pk>/', update_record, name='update_record'),
]

dockingRecords/models.py
from django.db import models
from locations.models import Stand
from accounts.models import CustomUser

# Solves the issue of having two foreign keys with the same model
class SecondOperator(models.Model):
    second_operator  = models.OneToOneField(CustomUser, blank=False, null=True, unique=True, on_delete=models.SET_NULL)

    def __str__(self):
        return f'{self.second_operator}'


class DockingRecord(models.Model):
    # Always required
    stand      = models.ForeignKey(Stand, blank=False, null=True, on_delete=models.SET_NULL)
    ac_type    = models.CharField(max_length=10, blank=False, null=False)
    ac_reg     = models.CharField(max_length=10, blank=False, null=False)
    # Required at docking
    operator1  = models.ForeignKey(CustomUser, blank=True, null=True, on_delete=models.SET_NULL)
    flight_no1 = models.CharField(max_length=10, blank=True, null=True)
    docked     = models.DateTimeField(blank=True, null=True)
    chocks_on  = models.TimeField(blank=True, null=True)
    # Required at undocking or no docking
    operator2    = models.ForeignKey(SecondOperator, blank=True, null=True, on_delete=models.SET_NULL)
    flight_no2   = models.CharField(max_length=10, blank=True, null=True)
    door_close   = models.TimeField(blank=True, null=True)
    b_door_close = models.TimeField(blank=True, null=True)
    c_door_close = models.TimeField(blank=True, null=True)
    undocked     = models.DateTimeField(blank=True, null=True)

    # not required but it tells the view how to read this record
    # false means this is a full record
    # true means this is an undocking record only, no docking was recorded for this flight
    no_docking = models.BooleanField(blank=True, null=True, default=False)
    # true means pbb b was used so make b_docked required
    b_used   = models.BooleanField(blank=True, null=True, default=False)
    # true means pbb c was used so make c_docked required
    c_used   = models.BooleanField(blank=True, null=True, default=False)

    # Required if b_used is true
    b_docked   = models.TimeField(blank=True, null=True)
    # Required if c_used is true
    c_docked   = models.TimeField(blank=True, null=True)
    # Required if b_used is true and undocking
    b_undocked = models.TimeField(blank=True, null=True)
    # Required if c_used is true and undocking
    c_undocked = models.TimeField(blank=True, null=True)
    
    remarks    = models.TextField(blank=True,  null=True)
    time_stamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.stand} - {self.operator1} - {self.ac_type} - {self.time_stamp}'

dockingRecords/views.py
# Django Classes
from django.shortcuts import render,redirect, get_object_or_404
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib import messages
from pathlib import Path
# My Classes
from .decorators import *
from ProjectManager.decorators import *
from .models import DockingRecord, SecondOperator
from .forms import *
from .filters import *
# Python
import requests
import json
from pathlib import Path

JSON_DIR = Path(__file__).resolve().parent

################################################################################################################################################################################
############################################################################# Records ##########################################################################################
################################################################################################################################################################################

@login_required(login_url='login')
@user_passes_test(view_records)
def flight_schedule(request):
    return render(request,"flight-schedule.html")

@login_required(login_url='login')
@user_passes_test(view_records)
def dockings(request):
    # limits records sent to the latest 20
    records_filter = RecordFilter(request.GET, DockingRecord.objects.filter())
    docking_records = DockingRecord.objects.all().order_by('-time_stamp')[:20]

    #if the user issued a filter request return the filtered data
    if request.method == "POST":
        # limite the results to protect the server from stupid enquiries that result in thousands of results
        record_filter = RecordFilter(request.POST, DockingRecord.objects.filter())
        if len(record_filter.qs) > 1000:
            #messages.warning(request, f"Too many Results {len(record_filter)}, try a more specific filter")
            context = {
                "docking_records":DockingRecord.objects.none(),
                "records_filter":records_filter,
                "total_records":f'Too many Results {len(record_filter.qs)}, try a more specific filter',
                }
            return render(request,'tables/docking-records-table.html', context)

        context = {
            "docking_records": record_filter.qs,
            "records_filter":records_filter,
            "total_records":len(record_filter.qs),
            }

        return render(request,'tables/docking-records-table.html', context)
    # else return all records
    context = {
        "docking_records":docking_records,
        "records_filter":records_filter,
        "total_records":len(docking_records),
        }
    return render(request,"dockings.html",context)

@login_required(login_url='login')
@user_passes_test(view_records)
def arrival_schedule(request):
    # get the sheduled flights list created by crontab
    fids_context = {}
    with open(f'{JSON_DIR}/json/fids_arr_dict.json') as f:
        fids_context['arr_schedule'] = json.load(f)

    return render(request,"arr_fids.html",fids_context)

@login_required(login_url='login')
@user_passes_test(view_records)
def departure_schedule(request):
    # get the sheduled flights list created by crontab
    fids_context = {}
    with open(f'{JSON_DIR}/json/fids_dep_dict.json') as f:
        fids_context['dep_schedule'] = json.load(f)

    return render(request,"dep_fids.html",fids_context)

@login_required(login_url='login')
@user_passes_test(view_records)
def search_records(request):
    if request.method == "POST":
        search_field  = request.POST.get('search-radios')
        record_filter = filter_records(request.POST.get('search-bar'),search_field)
        context       = {
            "docking_records": record_filter,
            "total_records":len(record_filter),
            }
    return render(request,'tables/docking-records-table.html', context)


@login_required(login_url='login')
@user_passes_test(add_records)
def create_docking_fids(request, iata):
    params = {
        'api_key': 'c5076a67-e3d7-474e-8f46-dc3949b2c9e4',
        'flight_iata': iata,
        'extra':'estimated',
        '_fields':'aircraft_icao,reg_number'
    }
    # request endpoint: schedules
    api_base = 'https://airlabs.co/api/v9/flights'
    api_result = requests.get(api_base, params)
    api_response = api_result.json()
    print(api_response)
    if request.method == 'POST':
        form = CreateDockingForm(request.POST, request=request)
        if form.is_valid():
            instance = form.save(commit=False)
            # saves the record to the logged in user in case they changed it in the browser
            instance.operator1 = CustomUser.objects.get(id = request.user.id)
            instance.save()
            return redirect('dockings')
    else:
        form = CreateDockingForm(initial={
            'flight_no1': iata,
            'ac_type': api_response['response'][0]['aircraft_icao'],
            'ac_reg': api_response['response'][0]['reg_number'],
        }, request=request)

    context = {
        "form":form,
        "current_user":request.user
        }

    return render(request,"create-docking.html",context)

@login_required(login_url='login')
@user_passes_test(add_records)
def create_docking(request):
    if request.method == 'POST':
        form = CreateDockingForm(request.POST, request=request)
        if form.is_valid():
            instance = form.save(commit=False)
            # saves the record to the logged in user in case they changed it in the browser
            instance.operator1 = CustomUser.objects.get(id = request.user.id)
            instance.save()
            return redirect('dockings')
    else:
        form = CreateDockingForm(request=request)

    context = {
        "form":form,
        # to show the username to the end user
        "current_user":request.user
        }

    return render(request,"create-docking.html",context)

@login_required(login_url='login')
@user_passes_test(add_records)
def create_nodocking(request):
    current_user = SecondOperator.objects.get(second_operator__id = request.user.id)
    if request.method == 'POST':
        form = CreateNoDockingForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            # saves the record to the logged in user in case they changed it in the browser
            instance.operator2 = current_user
            instance.no_docking = True
            instance.save()
            return redirect('dockings')
    else:
        form = CreateNoDockingForm()

    context = {
        "form":form,
        "current_user":current_user,
        }

    return render(request,"create-nodocking.html",context)

# This is actually an update Function
@login_required(login_url='login')
@user_passes_test(add_records)
def create_undocking(request, pk):
    record = get_object_or_404(DockingRecord, id = pk)

    if request.method == 'POST':
        form = CreateUndockingForm(request.POST, instance = record)
        if form.is_valid():
            instance = form.save(commit=False)
            user = CustomUser.objects.get(id = request.user.id)
            instance.operator2 = SecondOperator.objects.get(second_operator = user)
            instance.save()
            return redirect('dockings')
    else:
        form = CreateUndockingForm(instance=record)

    context = {
        "form":form,
        "current_user":request.user
        }

    return render(request,"create-undocking.html",context)

@login_required(login_url='login')
@user_passes_test(update_records)
def update_record(request, pk):
    record = get_object_or_404(DockingRecord, id = pk)

    if request.method == 'POST':
        form = UpdateRecordForm(request.POST, instance = record)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.save()
            return redirect('dockings')
    else:
        form = UpdateRecordForm(instance=record)

    context = {
        "form":form,
        }

    return render(request,"update-record.html",context)

############## DANGER SIGNS HERE!!!! ###################

#def copy_users(request):
#    users = CustomUser.objects.all()
#    for user in users:
#        new_user = SecondOperator(second_operator = user)
#        new_user.save()
#
#    return redirect('accounts')

dockingRecords/templates/tables/docking-records-table.html
<div class="table-container">
    <table class="table table-striped table-bordered table-hover">
        <caption>Total: {{ total_records }}</caption>
        <thead class="table-dark">
            <tr>
                <th class="align-middle" scope="col">Undock</th>
                <th class="align-middle" scope="col">Terminal</th>
                <th class="align-middle" scope="col">Stand</th>
                <th class="align-middle" scope="col">Arrival</th>
                {% comment %}
                <th class="align-middle" scope="col">Operator</th>
                <th class="align-middle" scope="col">Departure</th>
                <th class="align-middle" scope="col">Aircraft type</th>
                <th class="align-middle" scope="col">Aircraft Reg</th>
                <th class="align-middle" scope="col">Docked</th>
                <th class="align-middle" scope="col">UnDocked</th>
                <th class="align-middle" scope="col">Chocks On</th>
                <th class="align-middle" scope="col">Door Close</th>
                <th class="align-middle" scope="col">Edit</th>
                {% endcomment %}

            </tr>
        </thead>
        <tbody>

            {% for record in docking_records %}
                <tr>
                    <td class="align-middle">
                        {% if record.undocked or record.no_docking %}
                            <a href="#" class="disabled-link btn btn-success btn-sm border">Done</a>
                        {% else %}
                            <a href="{% url 'create_undocking' record.id %}" class="btn btn-primary btn">Undock</a>
                        {% endif %}
                    </td>
                    <td class="align-middle" id="{{ record.id }}One" data-bs-toggle="collapse" data-bs-target="#{{ record.id }}" aria-expanded="false" aria-controls="{{ record.id }}">{{ record.stand.gate_name.terminal_name }}</td>
                    <td class="align-middle" id="{{ record.id }}One" data-bs-toggle="collapse" data-bs-target="#{{ record.id }}" aria-expanded="false" aria-controls="{{ record.id }}">{{ record.stand }}</td>
                    <td class="align-middle" id="{{ record.id }}One" data-bs-toggle="collapse" data-bs-target="#{{ record.id }}" aria-expanded="false" aria-controls="{{ record.id }}">{{ record.flight_no1 }}</td>
                </tr>
                <tr id="{{ record.id }}" class="accordion-collapse collapse" aria-labelledby="{{ records.id }}One" data-bs-parent="#docking-records-table" style="">
                    <th class="align-middle table-warning" scope="col" colspan="2">Operator</th>
                    <th class="align-middle" scope="row" colspan="2">{{ record.operator1 }}</th>
                </tr>
                <tr id="{{ record.id }}" class="accordion-collapse collapse" aria-labelledby="{{ records.id }}One" data-bs-parent="#docking-records-table" style="">
                    <th class="align-middle table-warning" scope="col" colspan="2">Departure</th>
                    <td class="align-middle" colspan="2">{{ record.flight_no2 }}</td>
                </tr>
                <tr id="{{ record.id }}" class="accordion-collapse collapse" aria-labelledby="{{ records.id }}One" data-bs-parent="#docking-records-table" style="">
                    <th class="align-middle table-warning" scope="col" colspan="2">Aircraft type</th>
                    <td class="align-middle" colspan="2">{{ record.ac_type }}</td>
                </tr>
                <tr id="{{ record.id }}" class="accordion-collapse collapse" aria-labelledby="{{ records.id }}One" data-bs-parent="#docking-records-table" style="">
                    <th class="align-middle table-warning" scope="col" colspan="2">Aircraft Reg</th>
                    <td class="align-middle" colspan="2">{{ record.ac_reg }}</td>
                </tr>
                <tr id="{{ record.id }}" class="accordion-collapse collapse" aria-labelledby="{{ records.id }}One" data-bs-parent="#docking-records-table" style="">
                    <th class="align-middle table-warning" scope="col" colspan="2">Docked</th>
                    <td class="align-middle" colspan="2">{{ record.docked|date:"d-m-y | H:i" }}</td>
                </tr>
                <tr id="{{ record.id }}" class="accordion-collapse collapse" aria-labelledby="{{ records.id }}One" data-bs-parent="#docking-records-table" style="">
                    <th class="align-middle table-warning" scope="col" colspan="2">UnDocked</th>
                    <td class="align-middle" colspan="2">
                        {% if record.no_docking %}
                            No Docking
                        {% else %}
                            {{ record.undocked|date:"d-m-y | H:i" }}
                        {% endif %}
                    </td>
                </tr>
                <tr id="{{ record.id }}" class="accordion-collapse collapse" aria-labelledby="{{ records.id }}One" data-bs-parent="#docking-records-table" style="">
                    <th class="align-middle table-warning" scope="col" colspan="2">Chocks On</th>
                    <td class="align-middle" colspan="2">{{ record.chocks_on|date:"H:i" }}</td>
                </tr>
                <tr id="{{ record.id }}" class="accordion-collapse collapse" aria-labelledby="{{ records.id }}One" data-bs-parent="#docking-records-table" style="">
                    <th class="align-middle table-warning" scope="col" colspan="2">Door Close</th>
                    <td class="align-middle" colspan="2">{{ record.door_close|date:"H:i" }}</td>
                </tr>
                <tr id="{{ record.id }}" class="accordion-collapse collapse" aria-labelledby="{{ records.id }}One" data-bs-parent="#docking-records-table" style="">
                    <th class="align-middle table-warning" scope="col" colspan="2">Edit</th>
                    <td class="align-middle" colspan="2">
                        {% if perms.dockingRecords.delete_dockingrecord %}
                            <a href="{% url 'update_record' record.id %}" class="btn btn-secondary btn">Edit</a>
                        {% elif request.user == record.operator1 or request.user == record.operator2.second_operator %}
                            <a href="{% url 'update_record' record.id %}" class="btn btn-secondary btn">Edit</a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

dockingRecords/templates/tables/fids-arr-table.html
{% load new_filters %}

<div class="table-container">
    <table class="table table-striped table-bordered table-hover">
        <caption>Total: {{ total_records }}</caption>
        <thead class="table-dark">
            <tr>
                <th class="align-middle phone" scope="col">Flight_IATA</th>
                <th class="align-middle" scope="col">Dock</th>
                {% comment %}
                <th class="align-middle " scope="col">Status</th>
                <th class="align-middle phone" scope="col">From</th>
                <th class="align-middle " scope="col">Arr_Est_Time</th>
                <th class="align-middle phone" scope="col">Aircraft type</th>
                <th class="align-middle phone" scope="col">Aircraft Registration</th>
                <th class="align-middle phone" scope="col">Delayed</th>
                {% endcomment %}
            </tr>
        </thead>
        <tbody id="fids-table">
            {% for element in arr_schedule %}
                <tr>
                    <td class="align-middle phone" id="{{ element|get_value:'flight_iata' }}One" data-bs-toggle="collapse" data-bs-target="#{{ element|get_value:'flight_iata' }}" aria-expanded="false" aria-controls="{{ element|get_value:'flight_iata' }}">{{ element|get_value:'flight_iata' }}</td>
                    <td class="align-middle phone">
                        <a href="{% url 'create_docking_fids' element|get_value:'flight_iata' %}" class="btn btn-primary btn-sm">Dock</a>
                    </td>
                </tr>
                <tr id="{{ element|get_value:'flight_iata' }}" class="accordion-collapse collapse" aria-labelledby="{{ element|get_value:'flight_iata' }}One" data-bs-parent="#fids-table" style="">
                    <th class="align-middle table-warning" scope="col">Status</th>
                    {% if element|get_value:'status' == 'en-route' %}
                        <td class="align-middle phone" style="color: red;">{{ element|get_value:'status' }}</td>
                    {% elif element|get_value:'status' == 'landed' %}
                        <td class="align-middle phone" style="color: green;">{{ element|get_value:'status' }}</td>
                    {% elif element|get_value:'status' == 'scheduled' %}
                        <td class="align-middle phone" style="color: blue;">{{ element|get_value:'status' }}</td>
                    {% elif element|get_value:'status' == 'cancelled' %}
                        <td class="align-middle phone" style="color: grey;">{{ element|get_value:'status' }}</td>
                    {% endif %}
                </tr>
                <tr id="{{ element|get_value:'flight_iata' }}" class="accordion-collapse collapse" aria-labelledby="{{ element|get_value:'flight_iata' }}One" data-bs-parent="#fids-table" style="">
                    <th class="align-middle phone table-warning" scope="col">From</th>
                    <td class="align-middle phone">{{ element|get_value:'dep_iata' }}</td>
                </tr>
                <tr id="{{ element|get_value:'flight_iata' }}" class="accordion-collapse collapse" aria-labelledby="{{ element|get_value:'flight_iata' }}One" data-bs-parent="#fids-table" style="">
                    <th class="align-middle table-warning" scope="col">Arr_Estimated_Time</th>
                    <td class="align-middle phone">{{ element|unix_to_datetime:'arr_estimated_ts'|date:'H:i' }}</td>
                </tr>
                <tr id="{{ element|get_value:'flight_iata' }}" class="accordion-collapse collapse" aria-labelledby="{{ element|get_value:'flight_iata' }}One" data-bs-parent="#fids-table" style="">
                    <th class="align-middle table-warning" scope="col">Aircraft type</th>
                    <td class="align-middle">{{ element|get_value:'aircraft_icao' }}</td>
                </tr>
                <tr id="{{ element|get_value:'flight_iata' }}" class="accordion-collapse collapse" aria-labelledby="{{ element|get_value:'flight_iata' }}One" data-bs-parent="#fids-table" style="">
                    <th class="align-middle table-warning" scope="col">Aircraft Registration</th>
                    <td class="align-middle">{{ element|get_value:'reg_number' }}</td>
                </tr>
                
                <tr id="{{ element|get_value:'flight_iata' }}" class="accordion-collapse collapse" aria-labelledby="{{ element|get_value:'flight_iata' }}One" data-bs-parent="#fids-table" style="">
                    <th class="align-middle table-warning" scope="col">Delayed</th>
                    <td class="align-middle">
                        {% if element|get_value:'arr_delayed' == None %}
                            0
                        {% else%}
                            <u style="color:red;">{{ element|get_value:'arr_delayed' }}</u>
                        {% endif %}
                        Minutes
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

dockingRecords/templates/tables/fids-dep-table.html
{% load new_filters %}

<div class="table-container">
    <table class="table table-striped table-bordered table-hover">
        <caption>Total: {{ total_records }}</caption>
        <thead class="table-dark">
            <tr>
                <th class="align-middle phone" scope="col">Flight_IATA</th>
                <th class="align-middle " scope="col">Dep_Scheduled_Time</th>
                {% comment %}
                <th class="align-middle phone" scope="col">To</th>
                <th class="align-middle " scope="col">Dep_Scheduled_Time</th>
                <th class="align-middle " scope="col">Dep_Est_Time</th>
                <th class="align-middle phone" scope="col">Aircraft type</th>
                <th class="align-middle phone" scope="col">Aircraft Registration</th>
                <th class="align-middle phone" scope="col">Delayed</th>
                {% endcomment %}
            </tr>
        </thead>
        <tbody  id="fids-table">

            {% for element in dep_schedule %}
                <tr id="{{ element|get_value:'flight_iata' }}One" data-bs-toggle="collapse" data-bs-target="#{{ element|get_value:'flight_iata' }}" aria-expanded="false" aria-controls="{{ element|get_value:'flight_iata' }}">
                    <td class="align-middle">{{ element|get_value:'flight_iata' }}</td>
                    <td class="align-middle">{{ element|get_value:'dep_time' }}</td>
                </tr>
    
                <tr id="{{ element|get_value:'flight_iata' }}" class="accordion-collapse collapse" aria-labelledby="{{ element|get_value:'flight_iata' }}One" data-bs-parent="#fids-table" style="">
                    <th class="align-middle table-warning" scope="col">To</th>
                    <td class="align-middle">{{ element|get_value:'arr_iata' }}</td>
                </tr>

                <tr id="{{ element|get_value:'flight_iata' }}" class="accordion-collapse collapse" aria-labelledby="{{ element|get_value:'flight_iata' }}One" data-bs-parent="#fids-table" style="">
                    <th class="align-middle table-warning" scope="col">Status</th>
                    
                    {% if element|get_value:'status' == 'active' %}
                        <td class="align-middle" style="color: red;">{{ element|get_value:'status' }}</td>
                    {% elif element|get_value:'status' == 'landed' %}
                        <td class="align-middle" style="color: green;">{{ element|get_value:'status' }}</td>
                    {% elif element|get_value:'status' == 'scheduled' %}
                        <td class="align-middle" style="color: blue;">{{ element|get_value:'status' }}</td>
                    {% elif element|get_value:'status' == 'cancelled' %}
                        <td class="align-middle" style="color: grey;">{{ element|get_value:'status' }}</td>
                    {% endif %}
                </tr>
                
                <tr id="{{ element|get_value:'flight_iata' }}" class="accordion-collapse collapse" aria-labelledby="{{ element|get_value:'flight_iata' }}One" data-bs-parent="#fids-table" style="">
                    <th class="align-middle table-warning" scope="col">Dep_Est_Time</th>
                    <td class="align-middle">{{ element|get_value:'dep_estimated' }}</td>
                </tr>
                
                <tr id="{{ element|get_value:'flight_iata' }}" class="accordion-collapse collapse" aria-labelledby="{{ element|get_value:'flight_iata' }}One" data-bs-parent="#fids-table" style="">
                    <th class="align-middle table-warning" scope="col">Aircraft type</th>
                    <td class="align-middle">{{ element|get_value:'aircraft_icao' }}</td>
                </tr>
                
                <tr id="{{ element|get_value:'flight_iata' }}" class="accordion-collapse collapse" aria-labelledby="{{ element|get_value:'flight_iata' }}One" data-bs-parent="#fids-table" style="">
                    <th class="align-middle table-warning" scope="col">Aircraft Registration</th>
                    <td class="align-middle">{{ element|get_value:'reg_number' }}</td>
                </tr>
                
                <tr id="{{ element|get_value:'flight_iata' }}" class="accordion-collapse collapse" aria-labelledby="{{ element|get_value:'flight_iata' }}One" data-bs-parent="#fids-table" style="">
                    <th class="align-middle table-warning" scope="col">Delayed</th>
                    <td class="align-middle">
                        {% if element|get_value:'dep_delayed' == None %}
                            0 
                        {% else%}
                            <u style="color:red;">{{ element|get_value:'dep_delayed' }}</u> 
                        {% endif %}
                        Minutes
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>