accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from .views import *

urlpatterns = [
    # Accounts
    path('', accounts, name='accounts'),
    path('search_accounts', search_accounts, name='search_accounts'),
    path('create_account/', create_account, name='create_account'),
    path('update_account/<int:pk>/', update_account, name='update_account'),
    path('delete_account/<int:pk>/', delete_account, name='delete_account'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('deactivate_account/<int:pk>/', deactivate_account, name='deactivate_account'),
    # Password
    path('password_reset/',
        auth_views.PasswordResetView.as_view(
            template_name            = 'password/password_reset.html',
            html_email_template_name = 'email/password_reset_email.html',
            subject_template_name    = 'email/password_reset_subject.txt',
            ),
            name                     = 'password_reset'
        ),
    path('password_reset_done/', password_reset_done, name = 'password_reset_done'),
    path('reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            # success_url   = 'sign_in',
            template_name = 'password/password_reset_confirm.html',
            ),
            name          = 'password_reset_confirm'
        ),
    path('reset/done/', password_reset_complete, name = 'password_reset_complete'),
    path('password_change/',
        auth_views.PasswordChangeView.as_view(
            template_name = 'password/password_change.html',
            ),
            name          = 'password_change'
        ),
    path('password_change_done/', password_change_done, name = 'password_change_done'),
]

locations/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    # Terminals
    path('terminals/', terminals, name='terminals'),
    path('search_terminals/', search_terminals, name='search_terminals'),
    path('create_terminal/', create_terminal, name='create_terminal'),
    path('update_terminal/<int:pk>', update_terminal, name='update_terminal'),
    path('delete_terminal/<int:pk>', delete_terminal, name='delete_terminal'),
    # Gates
    path('gates/', gates, name='gates'),
    path('search_gates/', search_gates, name='search_gates'),
    path('create_gate/', create_gate, name='create_gate'),
    path('update_gate/<int:pk>', update_gate, name='update_gate'),
    path('delete_gate/<int:pk>', delete_gate, name='delete_gate'),
    # Stands
    path('stands/', stands, name='stands'),
    path('search_stands/', search_stands, name='search_stands'),
    path('create_stand/', create_stand, name='create_stand'),
    path('update_stand/<int:pk>', update_stand, name='update_stand'),
    path('delete_stand/<int:pk>', delete_stand, name='delete_stand'),
    # PBBs
    path('pbbs/', pbbs, name='pbbs'),
    path('search_pbbs/', search_pbbs, name='search_pbbs'),
    path('create_pbb/', create_pbb, name='create_pbb'),
    path('update_pbb/<int:pk>', update_pbb, name='update_pbb'),
    path('delete_pbb/<int:pk>', delete_pbb, name='delete_pbb'),
]

locations/models.py
from django.db import models

class Terminal(models.Model):
    terminal_name = models.CharField(max_length=50, blank=False, null=False)
    iata_code = models.CharField(max_length=10, blank=False, null=False, default='unset')
    icao_code = models.CharField(max_length=10, blank=False, null=False, default='unset')

    def __str__(self):
        return f'{self.iata_code}'

class Gate(models.Model):
    terminal_name = models.ForeignKey(Terminal, on_delete=models.CASCADE)
    gate_name     = models.CharField(max_length=50, blank=False, null=False)

    def __str__(self):
        return f'Gate {self.gate_name} | {self.terminal_name} |'

class Stand(models.Model):
    gate_name  = models.ForeignKey(Gate, on_delete=models.CASCADE)
    stand_name = models.CharField(max_length=50, blank=False, null=False)

    def __str__(self):
        return f'{self.stand_name}'

class Pbb(models.Model):
    stand_name = models.ForeignKey(Stand, on_delete=models.CASCADE)
    pbb_name   = models.CharField(max_length=50, blank=False, null=False)

    def __str__(self):
        return f'PBB {self.pbb_name} | {self.stand_name.gate_name.terminal_name} |'

locations/forms.py
from django import forms
from .models import *

class CreateTerminalForm(forms.ModelForm):
    class Meta:
        model = Terminal
        fields = [
            'terminal_name',
            'iata_code',
            'icao_code',
            ]

class UpdateTerminalForm(forms.ModelForm):
    class Meta:
        model = Terminal
        fields = [
            'terminal_name',
            'iata_code',
            'icao_code',
            ]

class CreateGateForm(forms.ModelForm):
    class Meta:
        model = Gate
        fields = [
            'terminal_name',
            'gate_name',
            ]

class UpdateGateForm(forms.ModelForm):
    class Meta:
        model = Gate
        fields = [
            'terminal_name',
            'gate_name',
            ]

class CreateStandForm(forms.ModelForm):
    class Meta:
        model = Stand
        fields = [
            'gate_name',
            'stand_name',
            ]

class UpdateStandForm(forms.ModelForm):
    class Meta:
        model = Stand
        fields = [
            'gate_name',
            'stand_name',
            ]

class CreatePbbForm(forms.ModelForm):
    class Meta:
        model = Pbb
        fields = [
            'stand_name',
            'pbb_name',
            ]

class UpdatePbbForm(forms.ModelForm):
    class Meta:
        model = Pbb
        fields = [
            'stand_name',
            'pbb_name',
            ]

locations/views.py
# Django Classes
from django.shortcuts import render,redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test
#My Classes
from .forms import *
from .models import *
from .filters import *
from ProjectManager.decorators import *
from .decorators import *


################################################################################################################################################################################
############################################################################# Terminals ########################################################################################
################################################################################################################################################################################

@login_required(login_url='login')
@user_passes_test(view_terminals)
def terminals(request):
    terminals       = Terminal.objects.all()
    terminal_filter = TerminalFilter(request.GET, Terminal.objects.filter().distinct())

    # if the user issued a filter request return the filtered data
    if request.method == "POST":
        terminal_filter = TerminalFilter(request.POST, Terminal.objects.filter().distinct())
        context         = {"terminals": terminal_filter.qs}
        return render(request,'tables/terminals-table.html', context)
    # else return all users data
    context = {
        "terminals":terminals,
        "terminal_filter":terminal_filter
        }

    return render(request,"terminals.html",context)

@login_required(login_url='login')
@user_passes_test(view_terminals)
def search_terminals(request):
    search_field  = request.POST.get('search-radios')
    record_filter = filter_terminals(request.POST.get('search-bar'), search_field)
    context       = {"terminals": record_filter}

    return render(request,'tables/terminals-table.html', context)

@login_required(login_url='login')
@user_passes_test(add_terminals)
def create_terminal(request):
    if request.method == 'POST':
        form = CreateTerminalForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('terminals')
    else:
        form = CreateTerminalForm()

    context = {
        "form":form,
        }

    return render(request,"create-terminal.html",context)

@login_required(login_url='login')
@user_passes_test(update_terminals)
def update_terminal(request, pk):
    terminal = get_object_or_404(Terminal, id = pk)

    if request.method == 'POST':
        form = UpdateTerminalForm(request.POST,instance=terminal)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.save()
            messages.info(request, f'{terminal.terminal_name} was successfully edited')
            return redirect('terminals')
    else:
        form = UpdateTerminalForm(instance=terminal)
    
    context = {
        'form': form,
        # sending the id for the delete
        'terminalid':terminal.id
    }

    return render(request, 'update-terminal.html', context)

@login_required(login_url='login')
@user_passes_test(delete_terminals)
def delete_terminal(request,pk):
    terminal = get_object_or_404(Terminal, id = pk)
    terminal.delete()
    messages.success(request, f'{terminal.terminal_name} and all records related to it were deleted, Good Job!')
    return redirect('terminals')

################################################################################################################################################################################
############################################################################# GATES ############################################################################################
################################################################################################################################################################################

@login_required(login_url='login')
@user_passes_test(view_gates)
def gates(request):
    gates = Gate.objects.all()
    gate_filter = GateFilter(request.GET, Gate.objects.filter().distinct())

    # if the user issued a filter request return the filtered data
    if request.method == "POST":
        gate_filter = GateFilter(request.POST, Gate.objects.filter().distinct())
        context = {
            "gates": gate_filter.qs,
            }
        return render(request,'tables/gates-table.html', context)
    # else return all gates data
    context = {
        "gates":gates,
        "gate_filter":gate_filter
        }

    return render(request,"gates.html",context)

@login_required(login_url='login')
@user_passes_test(view_gates)
def search_gates(request):
    search_field = request.POST.get('search-radios')
    record_filter = filter_gates(request.POST.get('search-bar'), search_field)
    context = {
        "gates": record_filter,
        }
    return render(request,'tables/gates-table.html', context)

@login_required(login_url='login')
@user_passes_test(add_gates)
def create_gate(request):
    if request.method == 'POST':
        form = CreateGateForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('gates')
    else:
        form = CreateGateForm()

    context = {
        "form":form,
        }

    return render(request,"create-gate.html",context)

@login_required(login_url='login')
@user_passes_test(update_gates)
def update_gate(request, pk):
    gate = get_object_or_404(Gate, id = pk)

    if request.method == 'POST':
        form = UpdateGateForm(request.POST,instance=gate)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.save()
            messages.info(request, f'{gate.gate_name} was successfully edited')
            return redirect('gates')
    else:
        form = UpdateGateForm(instance=gate)
    
    context = {
        'form': form,
        # sending the id for the delete
        'gateid':gate.id
    }

    return render(request, 'update-gate.html', context)

@login_required(login_url='login')
@user_passes_test(delete_gates)
def delete_gate(request,pk):
    gate = get_object_or_404(Gate, id = pk)
    gate.delete()
    messages.success(request, f'{gate.gate_name} and all records related to it were deleted!')
    return redirect('gates')

################################################################################################################################################################################
############################################################################# STANDS ###########################################################################################
################################################################################################################################################################################

@login_required(login_url='login')
@user_passes_test(view_stands)
def stands(request):
    stands = Stand.objects.all()
    stand_filter = StandFilter(request.GET, Stand.objects.filter().distinct())

    # if the user issued a filter request return the filtered data
    if request.method == "POST":
        stand_filter = StandFilter(request.POST, Stand.objects.filter().distinct())
        context = {
            "stands": stand_filter.qs,
            }
        return render(request,'tables/stands-table.html', context)
    # else return all stands data
    context = {
        "stands":stands,
        "stand_filter":stand_filter
        }

    return render(request,"stands.html",context)

@login_required(login_url='login')
@user_passes_test(view_stands)
def search_stands(request):
    search_field = request.POST.get('search-radios')
    record_filter = filter_stands(request.POST.get('search-bar'), search_field)
    context = {
        "stands": record_filter,
        }
    return render(request,'tables/stands-table.html', context)

@login_required(login_url='login')
@user_passes_test(add_stands)
def create_stand(request):
    if request.method == 'POST':
        form = CreateStandForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('stands')
    else:
        form = CreateStandForm()

    context = {
        "form":form,
        }

    return render(request,"create-stand.html",context)

@login_required(login_url='login')
@user_passes_test(update_stands)
def update_stand(request, pk):
    stand = get_object_or_404(Stand, id = pk)

    if request.method == 'POST':
        form = UpdateStandForm(request.POST,instance=stand)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.save()
            messages.info(request, f'{stand.stand_name} was successfully edited')
            return redirect('stands')
    else:
        form = UpdateStandForm(instance=stand)
    
    context = {
        'form': form,
        # sending the id for the delete
        'standid':stand.id
    }

    return render(request, 'update-stand.html', context)

@login_required(login_url='login')
@user_passes_test(delete_stands)
def delete_stand(request,pk):
    stand = get_object_or_404(Stand, id = pk)
    stand.delete()
    messages.success(request, f'{stand.stand_name} and all records related to it were deleted!')
    return redirect('stands')

################################################################################################################################################################################
############################################################################# PBBs #############################################################################################
################################################################################################################################################################################

@login_required(login_url='login')
@user_passes_test(view_pbbs)
def pbbs(request):
    pbbs = Pbb.objects.all()

locations/templates/htmx/delete-gate-modal.html
<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="ModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="ModalLabel">Delete gate</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>Deleting this Gate <b><u>{{ "will delete all records related to this Gate."|upper }}</u></b></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-success" data-bs-dismiss="modal">Cancel</button>
                <a href="{% url 'delete_gate' gateid %}" type="button" class="btn btn-danger">DELETE</a>
            </div>
        </div>
    </div>
</div>

locations/templates/htmx/delete-pbb-modal.html
<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="ModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="ModalLabel">Delete PBB</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>Deleting this PBB <b><u>{{ "will delete all records related to this PBB."|upper }}</u></b></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-success" data-bs-dismiss="modal">Cancel</button>
                <a href="{% url 'delete_pbb' pbbid %}" type="button" class="btn btn-danger">DELETE</a>
            </div>
        </div>
    </div>
</div>

locations/templates/htmx/delete-stand-modal.html
<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="ModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="ModalLabel">Delete Stand</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>Deleting this Stand <b><u>{{ "will delete all records related to this Stand."|upper }}</u></b></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-success" data-bs-dismiss="modal">Cancel</button>
                <a href="{% url 'delete_stand' standid %}" type="button" class="btn btn-danger">DELETE</a>
            </div>
        </div>
    </div>
</div>

locations/templates/htmx/delete-terminal-modal.html
<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="ModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="ModalLabel">Delete Terminal</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>Deleting this terminal <b><u>{{ "will delete all records related to this terminal."|upper }}</u></b></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-success" data-bs-dismiss="modal">Cancel</button>
                <a href="{% url 'delete_terminal' terminalid %}" type="button" class="btn btn-danger">DELETE</a>
            </div>
        </div>
    </div>
</div>

locations/templates/htmx/gates-filter.html
{% load widget_tweaks %}
{% load static %}

<form class="filter-form" method="post" enctype="multipart/form-data" action="" novalidate>
    {% csrf_token %}
    <table class="table table-striped table-bordered">
        <tbody>
            <tr class="filter-form mb-3">
                <td class="mb-3 fr-inp">
                    <label for="id_gate_name" class="form-label">Gate Name</label>
                    {% render_field gate_filter.form.gate_name  class="stop-enter form-control form-control-sm"%}
                </td>

                <td class="mb-3 fr-inp">
                    <label for="id_terminal_name" class="form-label">Terminal Name</label>
                    {% render_field gate_filter.form.terminal_name class="stop-enter form-select form-select-sm" %}
                </td>

                <td class="hidden">
                    <button type="button" class="btn btn-primary btn-lg"
                    hx-post="{% url 'gates' %}"
                    hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
                    hx-trigger="keydown[key=='Enter'] from:.filter-form" hx-target="#gates-table" hx-swap="innerHTML"
                    >Filter</button>
                </td>
            </tr>
        </tbody>
    </table>
</form>

locations/templates/htmx/gates-search-form.html
<form method="post" class="search-form" role="search">
    {% csrf_token %}
    <input type="text" class="stop-enter search-bar form-control form-control-sm" name="search-bar" placeholder="Search gates" aria-label="Search"
    hx-post="{% url 'search_gates' %}"
    hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
    hx-trigger="input delay:2s" hx-target="#gates-table" hx-swap="innerHTML">
    <div class="search-checks">
        <div class="btn-group btn-group-sm" role="group" aria-label="Basic radio toggle button group">
            <input type="radio" class="form-check-input btn-check" name="search-radios" id="gate_name" value="gate_name" checked="">
            <label class="btn btn-primary" for="gate_name">by <b>Gate Name</b></label>

            <input type="radio" class="form-check-input btn-check" name="search-radios" id="terminal_name" value="terminal_name">
            <label class="btn btn-primary" for="terminal_name">by <b>Terminal Name</b></label>
        </div>
    </div>
</form>
<script>
    function search_htmx() {
        const checkboxes = document.querySelectorAll('.form-check')
        checkboxes.forEach(box => {
           box.setAttribute("hx-post","{% url 'search_gates' %}");
           box.setAttribute("hx-headers", '{"X-CSRFToken": "{{ csrf_token }}"}');
           box.setAttribute("hx-trigger", "click");
           box.setAttribute("hx-target", "#gates-table");
           box.setAttribute("hx-swap", "innerHTML");
        })
     }
    search_htmx();
</script>

locations/templates/htmx/pbbs-filter.html
{% load widget_tweaks %}
{% load static %}

<form class="filter-form" method="post" enctype="multipart/form-data" action="" novalidate>
    {% csrf_token %}
    <table class="table table-striped table-bordered">
        <tbody>
            <tr class="filter-form mb-3">
                <td class="mb-3 fr-inp">
                    <label for="id_pbb_name" class="form-label">Pbb Name</label>
                    {% render_field pbb_filter.form.pbb_name class="stop-enter form-control" %}
                </td>
                
                <td class="mb-3 fr-inp">
                    <label for="id_stand_name" class="form-label">Stand Name</label>
                    {% render_field pbb_filter.form.stand_name class="stop-enter form-select"%}
                </td>

                <td class="mb-3 fr-inp">
                    <label for="id_gate_name" class="form-label">Gate Name</label>
                    {% render_field pbb_filter.form.gate_name class="stop-enter form-select"%}
                </td>
                
                <td class="mb-3 fr-inp">
                    <label for="id_terminal_name" class="form-label">Terminal Name</label>
                    {% render_field pbb_filter.form.terminal_name class="stop-enter form-select"%}
                </td>

                <td class="hidden">
                    <button type="button" class="btn btn-primary btn-lg"
                    hx-post="{% url 'pbbs' %}"
                    hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
                    hx-trigger="keydown[key=='Enter'] from:.filter-form" hx-target="#pbbs-table" hx-swap="innerHTML"
                    >Filter</button>
                </td>
            </tr>
        </tbody>
    </table>
</form>

locations/templates/htmx/pbbs-search-form.html
<form method="post" class="search-form" role="search">
    {% csrf_token %}
    <input type="text" class="stop-enter search-bar form-control form-control-sm" name="search-bar" placeholder="Search Passenger Boarding Bridges" aria-label="Search"
    hx-post="{% url 'search_pbbs' %}"
    hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
    hx-trigger="input delay:2s" hx-target="#pbbs-table" hx-swap="innerHTML">
    <div class="search-checks">
        <div class="btn-group btn-group-sm" role="group" aria-label="Basic radio toggle button group">
            <input type="radio" class="form-check-input btn-check btn-check" name="search-radios" id="pbb_name" value="pbb_name" checked="">
            <label class="btn btn-primary" for="pbb_name">by <b>Pbb Name</b></label>

            <input type="radio" class="form-check-input btn-check btn-check" name="search-radios" id="stand_name" value="stand_name">
            <label class="btn btn-primary" for="stand_name">by <b>Stand Name</b></label>

            <input type="radio" class="form-check-input btn-check btn-check" name="search-radios" id="gate_name" value="gate_name">
            <label class="btn btn-primary" for="gate_name">by <b>Gate Name</b></label>

            <input type="radio" class="form-check-input btn-check btn-check" name="search-radios" id="terminal_name" value="terminal_name">
            <label class="btn btn-primary" for="terminal_name">by <b>Terminal Name</b></label>
        </div>
    </div>
</form>
<script>
    function search_htmx() {
        const checkboxes = document.querySelectorAll('.form-check')
        checkboxes.forEach(box => {
           box.setAttribute("hx-post","{% url 'search_pbbs' %}");
           box.setAttribute("hx-headers", '{"X-CSRFToken": "{{ csrf_token }}"}');
           box.setAttribute("hx-trigger", "click");
           box.setAttribute("hx-target", "#pbbs-table");
           box.setAttribute("hx-swap", "innerHTML");
        })
     }
    search_htmx();
</script>

locations/templates/htmx/stands-filter.html
{% load widget_tweaks %}
{% load static %}

<form class="filter-form" method="post" enctype="multipart/form-data" action="" novalidate>
    {% csrf_token %}
    <table class="table table-striped table-bordered">
        <tbody>
            <tr class="filter-form mb-3">
                <td class="mb-3 fr-inp">
                    <label for="id_stand_name" class="form-label">Stand Name</label>
                    {% render_field stand_filter.form.stand_name class="stop-enter form-control" %}
                </td>

                <td class="mb-3 fr-inp">
                    <label for="id_gate_name" class="form-label">Gate Name</label>
                    {% render_field stand_filter.form.gate_name  class="stop-enter form-select"%}
                </td>

                <td class="mb-3 fr-inp">
                    <label for="id_terminal_name" class="form-label">Terminal Name</label>
                    {% render_field stand_filter.form.terminal_name  class="stop-enter form-select"%}
                </td>


                <td class="hidden">
                    <button type="button" class="btn btn-primary btn-lg"
                    hx-post="{% url 'stands' %}"
                    hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
                    hx-trigger="keydown[key=='Enter'] from:.filter-form" hx-target="#stands-table" hx-swap="innerHTML"
                    >Filter</button>
                </td>
            </tr>           
        </tbody>           
    </table>
</form>

locations/templates/htmx/stands-search-form.html
<form method="post" class="search-form" role="search">
    {% csrf_token %}
    <input type="text" class="stop-enter search-bar form-control form-control-sm" name="search-bar" placeholder="Search stands" aria-label="Search"
    hx-post="{% url 'search_stands' %}"
    hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
    hx-trigger="input delay:2s" hx-target="#stands-table" hx-swap="innerHTML">
    <div class="search-checks">
        <div class="btn-group btn-group-sm" role="group" aria-label="Basic radio toggle button group">
            <input type="radio" class="form-check-input btn-check" name="search-radios" id="stand_name" value="stand_name" checked="">
            <label class="btn btn-primary" for="stand_name">by <b>Stand Name</b></label>

            <input type="radio" class="form-check-input btn-check" name="search-radios" id="gate_name" value="gate_name">
            <label class="btn btn-primary" for="gate_name">by <b>Gate Name</b></label>

            <input type="radio" class="form-check-input btn-check" name="search-radios" id="terminal_name" value="terminal_name">
            <label class="btn btn-primary" for="terminal_name">by <b>Terminal Name</b></label>
        </div>
    </div>
</form>
<script>
    function search_htmx() {
        const checkboxes = document.querySelectorAll('.form-check')
        checkboxes.forEach(box => {
           box.setAttribute("hx-post","{% url 'search_stands' %}");
           box.setAttribute("hx-headers", '{"X-CSRFToken": "{{ csrf_token }}"}');
           box.setAttribute("hx-trigger", "click");
           box.setAttribute("hx-target", "#stands-table");
           box.setAttribute("hx-swap", "innerHTML");
        })
     }
    search_htmx();
</script>

locations/templates/htmx/terminals-filter.html
{% load widget_tweaks %}
{% load static %}

<form class="filter-form" method="post" enctype="multipart/form-data" action="" novalidate>
    {% csrf_token %}
    <table class="table table-striped table-bordered">
        <tbody>
            <tr class="filter-form mb-3">
                <td class="mb-3 fr-inp">
                    <label for="id_terminal_name" class="form-label">Terminal Name</label>
                    {% render_field terminal_filter.form.terminal_name class="stop-enter form-control form-control-sm" %}
                </td>

                <td class="mb-3 fr-inp">
                    <label for="id_iata_code" class="form-label">IATA Code</label>
                    {% render_field terminal_filter.form.iata_code  class="stop-enter form-control form-control-sm"%}
                </td>
            
                <td class="mb-3 fr-inp">
                    <label for="id_icao_code" class="form-label">ICAO Code</label>
                    {% render_field terminal_filter.form.icao_code class="stop-enter form-control form-control-sm" %}
                </td>

                <td class="hidden">
                    <button type="button" class="btn btn-primary btn-lg"
                    hx-post="{% url 'terminals' %}"
                    hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
                    hx-trigger="keydown[key=='Enter'] from:.filter-form" hx-target="#terminals-table" hx-swap="innerHTML"
                    >Filter</button>
                </td>
            </tr>
        </tbody>
    </table>
</form>